from pydantic import BaseModel, Field
from typing import List, Optional, Literal

class MappingRule(BaseModel):
    id: str
    name: Optional[str] = None
    source_field: Optional[str] = None
    xpath: Optional[str] = None
    type: Optional[str] = None
    required: Optional[bool] = False # Default to not required if missing
    max_length: Optional[int] = 0   # Default to no max length if missing
    severity: Optional[Literal['E', 'W']] = 'E' # Default to Error if missing
    description: Optional[str] = None
    target: Optional[dict] = None

class ExecutableRule(BaseModel):
    """
    A machine-readable, single validation step.
    Generated by the AI interpreter or from static rule properties.
    """
    id: str = Field(..., description="The ID of the parent MappingRule.")
    severity: Literal['E', 'W'] = Field(..., description="The severity of the rule (E for Error, W for Warning).")
    type: Literal['TYPE_CHECK', 'LENGTH_CHECK', 'REQUIRED_CHECK', 'VALUE_MAPPING', 'DEFAULT_VALUE', 'CUSTOM_LOGIC']
    source_column: str
    target_column: Optional[str] = None
    expected_value: Optional[str] = None
    # Add more fields as rule complexity grows, e.g.:
    # logic: Optional[str] = None # For 'CUSTOM_LOGIC'

class ValidationResult(BaseModel):
    rule_id: str
    severity: str
    status: Literal['Pass', 'Fail']
    csv_row: str
    csv_column: str
    field_value: Optional[str] = None
    expected: str
    actual: str
    message: str
